---
- name: Get messages list
  uri:
    url: "http://app:8080/messages"
    method: GET
    headers:
      Cookie: "{{ cookie_header }}"
    status_code: 200
  register: messages_list

- name: Assert messages page loaded
  assert:
    that:
      - messages_list.status == 200
